- name: clone_roles
  hosts: all
  become: true
  vars:
    git_repository: https://github.com/ptelega/ansible_roles
    git_branch: main

  tasks:
  - name: Create folder roles
    file:
      path: /etc/ansible/roles
      state: directory
      mode: "u=rwx,g=rwx,o=rx"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{ git_repository }}"
      dest: /etc/ansible/roles
      version: "{{ git_branch }}"